// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAESoft.Models;

#nullable disable

namespace SAESoft.Migrations
{
    [DbContext(typeof(DB_Context))]
    [Migration("20221222232225_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<int>("PermisosIdPermiso")
                        .HasColumnType("int");

                    b.Property<int>("RolesIdRol")
                        .HasColumnType("int");

                    b.HasKey("PermisosIdPermiso", "RolesIdRol");

                    b.HasIndex("RolesIdRol");

                    b.ToTable("PermisoRol");

                    b.HasData(
                        new
                        {
                            PermisosIdPermiso = 1,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 2,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 11,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 12,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 13,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 14,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 15,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 16,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 17,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 18,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 19,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 20,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 21,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 22,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 23,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 24,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 25,
                            RolesIdRol = 1
                        },
                        new
                        {
                            PermisosIdPermiso = 26,
                            RolesIdRol = 1
                        });
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Modulo", b =>
                {
                    b.Property<int>("IdModulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModulo"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaMod")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioMod")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdModulo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            IdModulo = 1,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7823),
                            Habilitado = true,
                            IdUsuarioCreacion = 1,
                            Nombre = "MENÚ PRINCIPAL"
                        },
                        new
                        {
                            IdModulo = 2,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7826),
                            Habilitado = true,
                            IdUsuarioCreacion = 1,
                            Nombre = "ADMINISTRACIÓN DEL SISTEMA"
                        },
                        new
                        {
                            IdModulo = 3,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7828),
                            Habilitado = true,
                            IdUsuarioCreacion = 1,
                            Nombre = "IMPORTACIONES"
                        });
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaMod")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioMod")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("IdModulo");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            IdPermiso = 1,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7860),
                            IdModulo = 1,
                            IdUsuarioCreacion = 1,
                            Nombre = "VER.ADMINISTRACION SISTEMA"
                        },
                        new
                        {
                            IdPermiso = 2,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7865),
                            IdModulo = 1,
                            IdUsuarioCreacion = 1,
                            Nombre = "VER.IMPORTACIONES"
                        },
                        new
                        {
                            IdPermiso = 11,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7866),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "VER.USUARIOS"
                        },
                        new
                        {
                            IdPermiso = 12,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7868),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "CREAR.USUARIOS"
                        },
                        new
                        {
                            IdPermiso = 13,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7869),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "MODIFICAR.USUARIOS"
                        },
                        new
                        {
                            IdPermiso = 14,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7895),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "ELIMINAR.USUARIOS"
                        },
                        new
                        {
                            IdPermiso = 15,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7897),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "VER.ROLES"
                        },
                        new
                        {
                            IdPermiso = 16,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7898),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "CREAR.ROLES"
                        },
                        new
                        {
                            IdPermiso = 17,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7900),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "MODIFICAR.ROLES"
                        },
                        new
                        {
                            IdPermiso = 18,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7903),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "ELIMINAR.ROLES"
                        },
                        new
                        {
                            IdPermiso = 19,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7904),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "VER.PERMISOS"
                        },
                        new
                        {
                            IdPermiso = 20,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7905),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "CREAR.PERMISOS"
                        },
                        new
                        {
                            IdPermiso = 21,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7908),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "MODIFICAR.PERMISOS"
                        },
                        new
                        {
                            IdPermiso = 22,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7909),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "ELIMINAR.PERMISOS"
                        },
                        new
                        {
                            IdPermiso = 23,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7911),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "VER.MODULOS"
                        },
                        new
                        {
                            IdPermiso = 24,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7912),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "CREAR.MODULOS"
                        },
                        new
                        {
                            IdPermiso = 25,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7914),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "MODIFICAR.MODULOS"
                        },
                        new
                        {
                            IdPermiso = 26,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7916),
                            IdModulo = 2,
                            IdUsuarioCreacion = 1,
                            Nombre = "ELIMINAR.MODULOS"
                        });
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaMod")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioMod")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(6257),
                            Habilitado = true,
                            IdUsuarioCreacion = 1,
                            Nombre = "Super Admin"
                        });
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaMod")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioMod")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Activo = true,
                            Apellidos = "Admin",
                            Email = "sa@sae-a.com",
                            FechaCreacion = new DateTime(2022, 12, 22, 17, 22, 24, 849, DateTimeKind.Local).AddTicks(7756),
                            IdRol = 1,
                            IdUsuarioCreacion = 1,
                            Nombres = "Super",
                            Password = "MtbCwdmMCtjF0V9gmsikMJ2tUwY9UPuUGqHoh5XfdsKgbW4c0lhIVeQ5kJYIlGeVMQDDDoko4EZ2xgoHuM7fq6zitYjOMQ==",
                            UserName = "sa"
                        });
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("SAESoft.Models.AdministracionSistema.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosIdPermiso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAESoft.Models.AdministracionSistema.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesIdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Permiso", b =>
                {
                    b.HasOne("SAESoft.Models.AdministracionSistema.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Usuario", b =>
                {
                    b.HasOne("SAESoft.Models.AdministracionSistema.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
