// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAESoft.Models;

#nullable disable

namespace SAESoft.Migrations
{
    [DbContext(typeof(DB_Context))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Super Admin"
                        });
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaMod")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioMod")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuarioCreacion");

                    b.HasIndex("IdUsuarioMod");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Activo = true,
                            Apellidos = "Admin",
                            Email = "sa@sae-a.com",
                            FechaCreacion = new DateTime(2022, 12, 15, 9, 37, 49, 261, DateTimeKind.Local).AddTicks(245),
                            IdRol = 1,
                            Nombres = "Super",
                            Password = "27T5a68SocpAbVjQfy5V47tm90grfKjLZbab/wVyvEFKUsjbB8KVa2TlpHuGyDGJhuc6sA4tMErYTJZ409U9qBPYgqo=",
                            UserName = "sa"
                        });
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Usuario", b =>
                {
                    b.HasOne("SAESoft.Models.AdministracionSistema.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAESoft.Models.AdministracionSistema.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("IdUsuarioCreacion");

                    b.HasOne("SAESoft.Models.AdministracionSistema.Usuario", "UsuarioMod")
                        .WithMany()
                        .HasForeignKey("IdUsuarioMod");

                    b.Navigation("Rol");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioMod");
                });

            modelBuilder.Entity("SAESoft.Models.AdministracionSistema.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
